// Ownership-hash continuity across the runtime migration. The fixture in
// fixtures/old-impl/ was generated by the pre-migration implementation
// (node:crypto + Buffer reads): identical file bytes must hash identically
// after the migration, or unchanged owned files would silently lose
// ownership (or, worse, gain it spuriously).
import { describe, expect, test } from 'bun:test';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from '../../src/posixpath.js';
import { hashContent, hashObject, readManifest } from '../../src/manifest.js';

const FIX = join(import.meta.dir, './fixtures/old-impl');

describe('old-implementation hash compatibility', () => {
  test('identical bytes reproduce the recorded ownership hashes', () => {
    const manifest = JSON.parse(readFileSync(join(FIX, 'manifest.json'), 'utf8'));
    for (const [rel, expected] of Object.entries(manifest.files)) {
      const bytes = readFileSync(join(FIX, rel.split('/').pop()));
      expect(hashContent(bytes)).toBe(expected);
    }
    const profile = JSON.parse(readFileSync(join(FIX, 'profile.json'), 'utf8'));
    const recorded = manifest.profiles.entries;
    const recordedId = Object.keys(recorded)[0];
    const entry = profile.daemon.agentProfiles.find((p) => p.id === recordedId);
    expect(entry).toBeDefined();
    expect(hashObject(entry)).toBe(recorded[recordedId]);
  });

  test('manifest shape from the old implementation still parses', async () => {
    const dir = mkdtempSync(join(Bun.env.TMPDIR ?? '/tmp', 'axstack-compat-'));
    writeFileSync(join(dir, '.axstack-manifest.json'), readFileSync(join(FIX, 'manifest.json'), 'utf8'));
    const parsed = await readManifest(dir);
    expect(parsed.version).toBe(1);
    expect(Object.keys(parsed.files).length).toBeGreaterThan(0);
    expect(parsed.profiles.path).toContain('paseo.json');
  });
});
