import { expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { sentences, requires, prohibits } from './prose-contract.js';

const read = (path) => readFileSync(`${import.meta.dir}/../../${path}`, 'utf8');
const runtime = () => read('skills/axstack/references/t3-runtime.md').replace(/[`*]/g, '').replace(/^#+.*$/gm, '').replace(/\|\n/g, '|.\n');
// Concepts co-occur in ONE sentence, in any order. Negative rules carry an
// explicit prohibition phrase; all other denial words still invalidate it.
const accepts = (text, [, concepts, prohibition]) => prohibition
  ? prohibits(text, prohibition, ...concepts) : requires(text, ...concepts);
const rules = [
  ['capabilities', [/driver/i, /T3 thread/i, /sav\w*/i, /orchestrator_capabilities/, /JSON/, /schema/i]],
  ['missing capability', [/missing capability/i, /hold/i, /affected operation/i], /without a substitute runtime/i],
  ['role snapshot', [/roles.json/, /snapshot/i, /preset/i, /stable role IDs/i, /requested/i, /resolved/i, /source/i, /time/i]],
  ['snapshot resume', [/resume/i, /snapshot/i], /no re-resolution/i],
  ['snapshot change', [/changes/i, /require/i, /user/i, /explicit decision/i]],
  ['provider mapping', [/bindings/i, /codex→codex/, /claude→claudeAgent/, /grok→grok/, /antigravity→antigravity/]],
  ['mode and options', [/modeId/, /runtimeMode:full-access/, /options:\[\{id,value\}\]/]],
  ['pinned model', [/preset model/i, /used|use/i, /as given/i]],
  ['class resolution', [/modelClass/, /resolve/i, /newest/i, /provider/i, /gpt-<N>-<class>/, /claude-<class>-<N>-<N>/]],
  ['resolution catalog', [/resolve-models.js/, /--provider/, /saved capabilities JSON path/i]],
  ['catalog hold', [/missing|malformed/i, /catalog/i, /hold/i, /resolution/i]],
  ['null model', [/model:null/, /first model/i, /provider/i, /saved capabilities/i], /no class/i],
  ['null ID receipt', [/record/i, /exact ID/i, /unresolved provider default/i]],
  ['availability hold', [/unavailable/i, /provider/i, /model/i, /role/i, /mode/i, /effort/i, /hold/i], /no substitution/i],
  ['no alternative on failure', [/auth/i, /quota/i, /timeout/i, /rejection/i, /alternative/i], /do not select|never select/i],
  ['absent seats', [/intentional/i, /absent seats/i, /recorded absences/i]],
  ['runtime availability', [/availability/i, /runtime proof/i]],
  ['codex effort', [/codex/i, /effort/i, /option ID/i, /reasoningEffort/]],
  ['claude effort', [/claude/i, /effort/i, /option ID effort/i]],
  ['grok effort', [/grok/i, /reasoningEffort/, /exclude max/i]],
  ['Grok CLI floor', [/CLI/, /requires|must/i, /≥1\.0\.13/]],
  ['Grok readiness proof', [/grok/i, /alone/i, /prove|establish/i, /CLI/i, /runs/i], /does not|cannot/i],
  ['opencode effort', [/opencode/i, /effort/i, /variant/], /no OpenCode role enters this migration/i],
  ['binding echo', [/dispatch echo/i, /match/i, /requested/i, /provider/i, /model/i]],
  ['binding readback', [/verify/i, /options/i, /runtimeMode/, /t3_thread_configuration/, /read.back/i]],
  ['separate binding evidence', [/record|keep/i, /requested/i, /effective/i, /separat/i]],
  ['worker proof', [/worker self.report/i, /configuration proof/i], /not|never/i],
  ['missing effort readback', [/missing effort read.back/i, /hold/i, /roles/i, /effort/i]],
  ['effort satisfaction', [/record/i, /satisfied/i], /never record/i],
  ['other effort limitation', [/other providers/i, /effort read.back/i, /unverified/i, /exercised|tested/i]],
  ['first configuration canary', [/first dispatch/i, /provider/i, /model/i, /effort/i, /running/i, /completed/i, /before/i, /siblings/i]],
  ['canary rejection', [/rejection/i, /stop|block/i, /siblings/i, /configuration/i]],
  ['unrelated configurations', [/unrelated configurations/i, /eligible|admissible/i]],
  ['read-only delegates', [/advisers/i, /research/i, /diligence/i, /delegate_task/, /async/i, /driver worktree/i, /title = dispatch key/i]],
  ['delegate untouched', [/tracked/i, /untracked/i, /files/i, /untouched/i]],
  ['delegate evidence', [/writes only/i, /<run>\/evidence\/<key>\//]],
  ['probe delegates', [/reviewers/i, /debug investigators/i, /execution investigators/i, /UI verifier/i, /delegate_task/, /async/i, /title = dispatch key/i]],
  ['probe checkout', [/disposable/i, /detached/i, /candidate SHA/i, /pinned base/i, /git worktree add --detach/]],
  ['probe cd', [/brief/i, /requires/i, /cd/i, /into it/i]],
  ['probe outputs', [/disposable probes/i, /outputs/i, /<run>\/evidence\/<key>\//]],
  ['writer launch', [/author/i, /code-arena/i, /t3_thread_launch/, /type:worktree/, /startFromOrigin:false/, /own worktree/i, /merges or closes/i]],
  ['owner row', [/owner/i, /driver thread/i, /driver worktree/i]],
  ['owner source exclusion', [/tracked files/i], /never (?:writes|edits|changes) tracked files|never (?:written|edited|changed)/i],
  ['owner worker exclusion', [/worker launch/i], /No worker launch/i],
  ['driver ownership', [/driver/i, /sole run.record writer/i, /one writer per candidate/i]],
  ['driver source exclusion', [/tracked files/i, /repairs/i, /author/i, /source/i], /never writes/i],
  ['repair ownership', [/repairs/i, /return|go back/i, /that author|same author/i]],
  ['idle ownership', [/missing/i, /idle/i, /session/i, /ownership/i, /transfer/i], /no ownership transfer|never (?:grant ownership transfer|transfers?)/i],
  ['driver preset exclusion', [/current/i, /chat\/driver|driver/i, /preset/i], /no role (?:row|entry)/i],
  ['key and title', [/dispatch key/i, /<run>:<role>:<task>:a<n>/, /before/i, /launch/i, /exact whole/i, /T3 title/i]],
  ['substring identity', [/substring matches/i, /establish/i, /identity/i], /do not|not/i],
  ['branch naming', [/branch/i, /axstack\/<run>\/<role>\/<task>-a<n>/]],
  ['branch encoding', [/lowercase/i, /each segment/i, /replace/i, /\[\^a-z0-9-\]/, /with -/]],
  ['dispatch original', [/dispatch key/i, /original form/i, /record both/i]],
  ['normalization identity', [/normalization/i, /identity substitute/i], /never/i],
  ['SHA baseRef', [/baseRef/, /branch name/i], /never (?:be )?a branch name/i],
  ['baseRef commit', [/always (?:be )?a commit SHA/i], /never a branch name|^(?!.*branch name)/i],
  ['pinned dispatch revisions', [/pin/i, /base/i, /candidate/i, /before/i, /dispatch/i]],
  ['receipt protocol', [/workers/i, /exactly one final marker/i, /AXSTACK-DONE key=/, /head=/, /report=/, /AXSTACK-FAILED key=/, /AXSTACK-QUESTION key=/, /q=/]],
  ['report identity', [/reports/i, /absolute/i, /private evidence paths/i]],
  ['report-only head', [/report.only head/i, /pinned candidate SHA/i]],
  ['writer delivery', [/launched writers/i, /marker/i, /t3_thread_send/, /recorded driver thread/i]],
  ['delegate delivery', [/delegated children/i, /final result/i]],
  ['status persistence', [/driver/i, /persist/i, /task_status/, /private evidence/i, /before/i, /t3_thread_read/, /delegated task/i]],
  ['whole status', [/save/i, /whole response/i, /before/i, /consum|expand/i, /result/i]],
  ['delegate completion', [/delegated completion/i, /require/i, /terminal/i, /completed/, /result_available/, /hasPendingChildRuns:false/, /AXSTACK-DONE/]],
  ['question incomplete', [/question/i, /incomplete/i, /completed/i]],
  ['writer completion', [/launched writer completion/i, /require/i, /terminal/i, /t3_thread_wait/, /non.empty diff/i, /clean tree/i, /red\/green/i]],
  ['message progress', [/receipt message alone/i, /only/i, /progress/i]],
  ['current completion', [/completion/i, /current attempt key/i, /candidate SHA/i]],
  ['stale completion', [/older attempt/i, /complet\w*/i, /newer/i], /never/i],
  ['stale receipt evidence', [/stale/i, /duplicate receipts/i, /evidence/i, /deduplicated/i, /runtime identity/i]],
  ['delivery validation', [/whole delivery/i, /before/i, /acknowledgment/i, /advance only after/i, /sender/i, /scope/i, /artifacts/i]],
  ['failure classification', [/task_status failed/, /failed or interrupted/i, /preparing thread error/i, /AXSTACK-FAILED/, /incomplete outcome/i, /preserved evidence/i]],
  ['silence completion', [/silence/i, /successful completion/i], /not|never/i],
  ['delegated isolation', [/after each delegated completion/i, /driver/i, /HEAD/, /git status --porcelain/, /pre-dispatch/i, /unchanged/i, /untracked/i]],
  ['isolation hold', [/any change/i, /is a hold/i, /before/i, /advancing/i]],
  ['launch recovery inventory', [/lost launch response/i, /fully paginated/i, /t3_thread_list/, /titleContains=<key>/, /exact whole.title equality/i, /git worktree list/]],
  ['reserved branch', [/keep/i, /reserved branch/i, /recovery/i]],
  ['unreconciled worktree', [/branch/i, /worktree/i, /without a reconciled thread/i, /prevent\w*/i, /proof of absence/i], /without a reconciled thread/i],
  ['launch recovery outcomes', [/recovery/i, /adopt/i, /one exact match/i, /worktree/i, /branch/i, /agree/i]],
  ['relaunch absence', [/proven absence/i, /relaunch once/i, /same reserved key/i, /branch/i]],
  ['recovery hold', [/several matches/i, /conflicts/i, /second uncertain response/i, /incomplete inventory/i, /hold/i]],
  ['silence duplicate', [/duplicate writer/i, /silence/i, /launch|start|justif/i], /never/i],
  ['post-launch wait', [/post.launch/i, /driver/i, /t3_thread_wait/, /timeoutMs:120000/, /failed/i, /launch failure/i]],
  ['timed-out started', [/timed.out/i, /t3_thread_read/, /activeRunId/, /worktreePath/, /started/i]],
  ['preparing hold', [/still preparing/i, /is a hold/i, /re.read/i, /next wake/i]],
  ['unresolved launch', [/unresolved state/i, /preserve|retain/i, /attempt/i]],
  ['question resume', [/AXSTACK-QUESTION/, /answer once/i, /t3_thread_send/, /childThreadId/, /resumed runId/i, /t3_thread_wait/, /timeoutMs:600000/, /run watch/i]],
  ['resumed result', [/persist status/i, /accept only/i, /latestTerminal/, /newer than/i, /question run/i, /terminal success/i, /matching receipt key\/SHA/i], /not lexical ID order/i],
  ['question summary', [/original summary/i, /stable/i]],
  ['question notification', [/notification/i], /no notification/i],
  ['same writer repair', [/repair/i, /t3_thread_send/, /mode:queue/, /same author/i, /same attempt/i, /worktree/i]],
  ['repair revision', [/pin/i, /new candidate revision/i]],
  ['replacement attempt', [/replacement/i, /terminal failure/i, /a<n\+1>/, /new branch/i, /title/i]],
  ['failed branch salvage', [/failed attempt/i, /branch/i, /kept/i, /until salvage/i]],
  ['unknown writer liveness', [/unknown liveness/i, /holds/i, /replacement/i]],
  ['replacement reconcile', [/reconcile/i, /old writer/i, /before/i, /another/i]],
  ['idle writer watch', [/unsettled launched thread/i, /turn/i, /end only/i, /schedule_task/, /bindToCurrentThread:true/, /everyMs:600000/, /armed/i, /ID recorded/i]],
  ['watch reconcile', [/each wake/i, /reconcile all unsettled runs/i, /writer/i, /died/i, /without sending|silently/i]],
  ['watch failure', [/failed runs/i, /hold|held/i, /incomplete work/i]],
  ['watch deletion', [/nothing/i, /unsettled/i, /delete_scheduled_task/, /list_scheduled_tasks/, /read back/i, /absence/i]],
  ['uncertain watch deletion', [/uncertain delete/i, /preserve|retain/i, /hold/i, /recorded ID/i]],
  ['safe deletion in briefs', [/put|include/i, /safe.deletion rule/i, /every worker brief/i]],
  ['named private evidence', [/name|identify/i, /private/i, /<run>\/evidence\/<key>\//, /brief/i, /completion receipt/i]],
  ['temporary evidence guard', [/before/i, /use/i, /cleanup/i, /TMPDIR/, /0700/, /owned/i, /real path/i, /inside/i, /recorded run evidence/i, /owner/i], /no symlink/i],
  ['worktree path guards', [/equivalent guards/i, /worktree.local paths/i]],
  ['uncertain path retention', [/uncertain paths/i, /preserved/i, /reconciliation/i]],
  ['safe deletion', [/deletion/i, /exact validated owned path/i, /evidence/i, /TMPDIR/, /worktree/i, /literal absolute path/i, /\$\{VAR:\?\}/, /no glob/i, /no parent.root deletion/i], /no glob|no parent.root deletion/gi],
  ['glob deletion', [/no glob/i, /no parent.root deletion/i], /no glob|no parent.root deletion/gi],
  ['parent deletion', [/no parent.root deletion/i, /no glob/i], /no glob|no parent.root deletion/gi],
  ['cache deletion', [/general cache/i], /never wipe a general cache/i],
  ['cache evidence', [/incidental caches/i, /evidence/i], /not/i],
  ['brief confirmation', [/dispatching owner/i, /confirm/i, /brief question once/i, /existing authority/i, /re.verify/i, /started/i]],
  ['second brief hold', [/second ask/i, /holds/i]],
  ['prompt refusal', [/answer/i, /trust/i, /permission prompts/i], /never/i],
  ['confirmation authority', [/brief confirmation/i, /no authority/i, /harness/i, /tool dialog/i, /does not answer/i], /no authority|does not answer/gi],
  ['prompt refusal hold', [/permission prompt/i, /provider safety refusal/i, /held/i, /incomplete outcome/i]],
  ['refusal bypass', [/bypass/i, /retry/i, /another model/i], /never/i],
  ['additional prompt holds', [/trust/i, /hook review/i, /authentication/i, /model prompts/i, /hold/i]],
  ['prompt recovery evidence', [/preserve/i, /attempt/i, /inspect/i, /native state/i, /before/i, /authorized recovery/i]],
  ['review evidence isolation', [/each reviewer/i, /separate checkout/i, /private evidence folder/i], /no first-pass cross-read/i],
  ['review tracked files', [/tracked candidate files/i, /read.only/i]],
  ['review evidence readback', [/read back/i, /report/i, /supporting evidence/i, /before/i, /removing/i, /checkout/i]],
  ['external evidence', [/evidence/i, /outside/i, /archive/i], /no archive/i],
  ['fresh review', [/later review/i, /fresh checkout/i]],
  ['fresh review retention', [/unknown/i, /active evidence/i, /unique bytes/i, /preserved/i]],
  ['untracked retention', [/untracked files/i, /worktree/i, /disposable/i, /prov|establish/i], /never|cannot/i],
  ['terminal evidence retention', [/T3 terminal state alone/i, /discarding evidence/i, /authoriz/i], /does not|cannot|not/i],
  ['acceptance distinct from start', [/input acceptance/i, /started state/i, /effective settings/i, /completed work/i, /distinct evidence/i]],
  ['silence exit', [/silence/i, /contact loss/i, /idle state/i, /prov\w*/i, /exit/i], /never/i],
  ['resume ownership', [/ordinary resume/i, /same owner/i, /author/i, /attempt/i, /worktree/i, /revisions/i, /pending receipts/i]],
  ['uncertain replacement', [/uncertainty/i, /holds/i, /replacement/i]],
  ['ownership transfer', [/explicit user transfer/i, /recipient acceptance/i, /session/i, /scope/i, /revision/i, /authority/i, /before/i, /ownership/i]],
  ['current owner accountability', [/current owner/i, /accountab\w*/i, /until then/i]],
  ['prior owner stop', [/prior owner/i, /stops/i, /after acceptance/i]],
  ['transfer receipt boundary', [/input acceptance/i, /turn start alone/i, /transfer receipt/i], /no transfer receipt|cannot be a transfer receipt/i],
  ['runtime identity mismatch', [/T3/, /threadId\/runId/, /mismatch/i, /stop consuming/i, /reconcile/i, /driver identity/i, /native state/i]],
  ['identity forgery', [/forg\w*/i, /sender/i, /borrow\w*/i, /identity/i, /bypass/i, /mismatch/i], /never/i],
  ['user takeover retention', [/driver/i, /retain/i, /user.taken.over T3 thread/i]],
  ['user takeover cleanup', [/cleanup commands/i, /t3_thread_organize/, /settle/i, /archive/i], /never send/i],
  ['T3 settle evidence', [/require/i, /T3 terminal run evidence/i, /before/i, /t3_thread_organize/, /settle/i, /archive/i]],
  ['T3 metadata boundary', [/metadata actions/i, /worktree removal/i], /not/i],
  ['cleanup preflight', [/worktreeCleanup/, /off/, /every Axstack project/i]],
  ['cleanup readback', [/preflight/i, /t3_project_read/, /where exposed/i]],
  ['cleanup limitation', [/otherwise/i, /record a limitation/i, /documented/i, /installation setup step/i]],
  ['cleanup evidence priority', [/automatic worktree deletion/i, /evidence readback/i, /salvage/i], /cannot replace|no substitute for/i],
  ['run record', [/run record/i, /driver threadId/, /projectId/, /host/i, /T3 version/, /installed Axstack SHA/, /capabilities JSON path/, /scheduledTaskIds/, /watch/i, /manager schedule/i]],
  ['dispatch target record', [/per dispatch/i, /record/i, /key/i, /mechanism/i, /requested target/i, /read.back/i]],
  ['dispatch identity record', [/taskId\/childThreadId\/childRunId/, /threadId\/runId\/worktree\/branch\/base SHA/]],
  ['dispatch revision record', [/checkout path/i, /candidate/i, /base SHAs/i]],
  ['dispatch evidence record', [/evidence folder/i, /scope\/authority/i, /owner/i, /pending receipts/i, /hold/i, /Next/]],
  ['native runtime boundary', [/boundary/i, /Axstack daemon/i, /DB/, /lock/i, /scheduler/i], /no Axstack daemon/i],
  ['publication authority', [/private evidence/i, /requires/i, /explicit publication authority/i, /before sharing/i]],
  ['receipt authority', [/receipts/i, /merge/i, /release/i, /publication/i, /model.substitution/i, /host.mutation/i, /expanded scope authority/i], /no merge/i],
  ['human merge authority', [/human/i, /merges/i, /by default/i]],
];

// Separate editorial holdout: passive voice, reordered operands, and synonyms.
// These sentences are fixtures, not pattern templates or per-rule inversions.
const holdouts = [
  'The orchestrator_capabilities JSON is saved by the driver, a T3 thread, which follows the schema.',
  'Without a substitute runtime, the affected operation holds for missing capability.',
  'Source, time and resolved ID accompany the requested settings and stable role IDs in a snapshot of the selected preset from roles.json.',
  'With no re-resolution, the snapshot is preserved on resume.',
  "The user's explicit decision is required for changes.",
  'Bindings are antigravity→antigravity, grok→grok, claude→claudeAgent and codex→codex.',
  'Use options:[{id,value}] and map modeId into runtimeMode:full-access.',
  'As given, the preset model is used.',
  'For each provider, modelClass resolves the newest catalog entry matching claude-<class>-<N>-<N> or gpt-<N>-<class>.',
  'The saved capabilities JSON path is passed to resolve-models.js with --provider.',
  'Resolution holds for a malformed or missing catalog.',
  'Saved capabilities for the provider supply the first model for model:null with no class.',
  'Record the exact ID rather than an unresolved provider default.',
  'With no substitution, hold an unavailable effort, mode, role, model or provider.',
  'An alternative is never selected for rejection, timeout, quota or auth.',
  'Recorded absences are retained for intentional absent seats.',
  'Runtime proof establishes availability.',
  'Option ID reasoningEffort supplies Codex effort.',
  'Option ID effort supplies Claude effort.',
  'Exclude max for Grok using reasoningEffort.',
  'The CLI must satisfy ≥1.0.13.',
  'That its CLI runs cannot be established by Grok advertising alone.',
  'With no OpenCode role enters this migration, OpenCode effort uses variant.',
  'The requested model and provider match the dispatch echo.',
  'Read-back through t3_thread_configuration must verify runtimeMode and options.',
  'Keep effective and requested values in separate records.',
  'Configuration proof is never a worker self-report.',
  'Roles needing effort hold on missing effort read-back.',
  'Never record it as satisfied.',
  'Until tested, effort read-back for other providers stays unverified.',
  'Before siblings launch, the first dispatch of a provider, model and effort reaches a completed or running run.',
  'Siblings for that configuration are blocked by rejection.',
  'Eligible configurations include unrelated configurations.',
  'In the driver worktree, advisers, diligence and research use async delegate_task with title = dispatch key.',
  'Untracked and tracked files remain untouched.',
  'The delegate writes only <run>/evidence/<key>/.',
  'UI verifier, execution investigators, debug investigators and reviewers use async delegate_task with title = dispatch key.',
  'Use git worktree add --detach for a disposable detached checkout pinned to candidate SHA and pinned base.',
  'Into it the brief requires cd.',
  'Only disposable probes write there, and outputs go to <run>/evidence/<key>/.',
  'Until the PR merges or closes, author and code-arena retain their own worktree, launched by t3_thread_launch with startFromOrigin:false and type:worktree.',
  'The Owner is the Driver thread in the Driver worktree.',
  'Tracked files are never edited.',
  'No worker launch applies.',
  'One writer per candidate is enforced by the driver as sole run-record writer.',
  "The driver never writes tracked files or repairs an author's source.",
  'Repairs go back to the same author.',
  'Ownership never transfers because a session is missing or idle.',
  'In any preset, the current driver has no role entry.',
  'Before launch, record dispatch key <run>:<role>:<task>:a<n> as the exact whole T3 title.',
  'Identity is not established by substring matches.',
  'Use axstack/<run>/<role>/<task>-a<n> as the branch.',
  'Replace [^a-z0-9-] with - and lowercase each segment.',
  'Record both while retaining the dispatch key in its original form.',
  'An identity substitute is never normalization.',
  'baseRef must never be a branch name.',
  'It is always a commit SHA.',
  'Before dispatch, pin the candidate and base.',
  'Workers provide exactly one final marker, AXSTACK-QUESTION key= q=, AXSTACK-FAILED key= head= report=, or AXSTACK-DONE key= head= report=.',
  'Absolute private evidence paths are used in reports.',
  'The pinned candidate SHA is the report-only head.',
  'Through t3_thread_send, launched writers send the marker to the recorded driver thread.',
  'In their final result, delegated children leave the receipt.',
  'Before any t3_thread_read for that delegated task, the driver must persist task_status in private evidence.',
  'Before expanding or consuming the result, save the whole response.',
  'Terminal completed with AXSTACK-DONE, hasPendingChildRuns:false and result_available is required for delegated completion.',
  'Even if completed, a question remains incomplete.',
  'Launched writer completion requires red/green logs, clean tree, non-empty diff and terminal t3_thread_wait.',
  'Only progress is proved by a receipt message alone.',
  'The candidate SHA and current attempt key govern completion.',
  'A newer attempt is never completed by an older attempt.',
  'Stale or duplicate receipts are kept as evidence, deduplicated by runtime identity.',
  'Before acknowledgment, process the whole delivery and advance only after checking artifacts, scope and sender.',
  'Preserved evidence and an incomplete outcome apply to AXSTACK-FAILED, preparing thread error, failed or interrupted run or task_status failed.',
  'Successful completion is never established by silence.',
  'After each delegated completion, the driver compares git status --porcelain including untracked entries and HEAD to pre-dispatch values, which stay unchanged.',
  'Before advancing work, any change is a hold.',
  'For a lost launch response combine git worktree list and fully paginated t3_thread_list titleContains=<key>, filtered by exact whole-title equality.',
  'Through recovery keep the reserved branch.',
  'Proof of absence is prevented by a branch or worktree without a reconciled thread.',
  'In recovery, adopt one exact match when branch and worktree agree.',
  'With the same reserved key and branch, relaunch once on proven absence.',
  'Hold on incomplete inventory, second uncertain response, conflicts or several matches.',
  'Silence never justifies launching a duplicate writer.',
  'Post-launch, the driver calls t3_thread_wait timeoutMs:120000 and classifies failed as launch failure.',
  'Started is established on timed-out when t3_thread_read shows worktreePath and activeRunId.',
  'Still preparing is a hold, to re-read at the next wake.',
  'The attempt is retained in unresolved state.',
  'For AXSTACK-QUESTION, answer once via t3_thread_send to childThreadId, recording resumed runId then t3_thread_wait timeoutMs:600000 re-armed by run watch.',
  'Persist status and accept only latestTerminal* with terminal success and matching receipt key/SHA, newer than the question run by recorded ordering, not lexical ID order.',
  'Stable is the original summary.',
  'No notification is assumed.',
  'A repair uses t3_thread_send mode:queue in the same worktree, same attempt and same author.',
  'The new candidate revision is pinned.',
  'Terminal failure permits replacement using a<n+1>, a new title and new branch.',
  "Until salvage, the failed attempt's branch is kept.",
  'Replacement holds when there is unknown liveness.',
  'Before another writer, reconcile the old writer.',
  'With an unsettled launched thread, the turn can end only with schedule_task bindToCurrentThread:true everyMs:600000 armed and ID recorded.',
  'Each wake must reconcile all unsettled runs, including a writer that died silently.',
  'Incomplete work is held when failed runs occur.',
  'When nothing is unsettled, delete_scheduled_task and read back absence with list_scheduled_tasks.',
  'The hold and recorded ID are retained on an uncertain delete.',
  'In every worker brief, include the Safe-deletion rule.',
  'In the completion receipt and brief, identify the private <run>/evidence/<key>/ folder.',
  'Before cleanup or use, TMPDIR is an owned 0700 directory, real path inside recorded run evidence, no symlink and matching owner.',
  'For worktree-local paths, apply equivalent guards.',
  'Preserved uncertain paths await reconciliation.',
  'With no parent-root deletion and no glob, deletion uses a literal absolute path or ${VAR:?} for an exact validated owned path in the worktree, TMPDIR or evidence.',
  'No glob and no parent-root deletion are permitted.',
  'No parent-root deletion and no glob are allowed.',
  'Never wipe a general cache.',
  'Evidence is not incidental caches.',
  'The dispatching owner must re-verify started after confirming the brief question once and restating existing authority.',
  'A second ask holds.',
  'Trust or permission prompts are never answered.',
  'Brief confirmation adds no authority and does not answer a harness or tool dialog.',
  'A provider safety refusal or permission prompt is an incomplete outcome held for resolution.',
  'Never retry or bypass through another model.',
  'Model prompts, authentication, hook review and trust all hold.',
  'Before authorized recovery, inspect native state and preserve the attempt.',
  'Each reviewer receives a private evidence folder and separate checkout with no first-pass cross-read.',
  'Read-only are the tracked candidate files.',
  'Before removing that checkout, read back supporting evidence and report.',
  'No archive is needed for evidence outside it.',
  'A fresh checkout is used for later review.',
  'Preserved unique bytes include unknown or active evidence.',
  'A worktree is never proven disposable by its untracked files.',
  'Discarding evidence is not authorized by T3 terminal state alone.',
  'Distinct evidence includes completed work, effective settings, started state and input acceptance.',
  'Exit is never proved by idle state, contact loss or silence.',
  'Ordinary resume retains pending receipts and revisions with the same owner, author, attempt and worktree.',
  'Replacement holds on uncertainty.',
  'Before ownership changes, explicit user transfer validates recipient acceptance against authority, revision, scope and session.',
  'Until then, accountability remains with the current owner.',
  'After acceptance, the prior owner stops.',
  'Turn start alone or input acceptance cannot be a transfer receipt.',
  'With a T3 threadId/runId mismatch, stop consuming and reconcile the driver identity with native state.',
  'Never bypass the mismatch by borrowing an identity or forging a sender.',
  'A user-taken-over T3 thread is retained by the driver.',
  'Never send cleanup commands to it, including t3_thread_organize settle or archive.',
  'Before t3_thread_organize settle or archive, require T3 terminal run evidence.',
  'Worktree removal is not performed by these metadata actions.',
  'For every Axstack project worktreeCleanup is off.',
  'Where exposed, preflight uses t3_project_read.',
  'Otherwise, record a limitation pointing to the documented installation setup step.',
  'Automatic worktree deletion cannot replace salvage and evidence readback.',
  'Host, driver threadId, projectId, T3 version, installed Axstack SHA, capabilities JSON path and scheduledTaskIds for each watch and manager schedule belong in the run record.',
  'Per dispatch, requested target, read-back, mechanism and key appear in the record.',
  'Use taskId/childThreadId/childRunId or threadId/runId/worktree/branch/base SHA.',
  'Base SHAs and candidate accompany the checkout path.',
  'Next and hold join pending receipts, owner, scope/authority and evidence folder.',
  'The boundary has no Axstack daemon, DB, lock or scheduler.',
  'Before sharing, private evidence requires explicit publication authority.',
  'Receipts grant no merge, release, publication, model-substitution, host-mutation or expanded scope authority.',
  'By default the human merges.',
];

// The same transformations apply to every rule; none are authored per rule.
const transformations = [
  [/\bmust\b/gi, 'must not'], [/\bshall\b/gi, 'shall not'],
  [/\brequires?\b/gi, 'does not require'], [/\brequired\b/gi, 'not required'],
  [/\bnever\b/gi, 'always'], [/\balways\b/gi, 'never'],
  [/\bno\b/gi, 'some'], [/\bnot\b/gi, 'indeed'], [/\bcannot\b/gi, 'can'],
  [/\bwithout\b/gi, 'with'], [/\bbefore\b/gi, 'after'],
  [/\bis a hold\b/gi, 'is not a hold'], [/\b(?:holds?|held)\b/gi, 'proceeds'],
  [/commit SHA|branch name/gi, (word) => /commit/i.test(word) ? 'branch name' : 'commit SHA'],
  [/:(?:false|true)\b/g, (word) => word === ':false' ? ':true' : ':false'],
  [/\bexclude\b/gi, 'include'],
];
const inversions = (text) => [...transformations.map(([pattern, replacement]) => text.replace(pattern, replacement)),
  `Do not follow this instruction: ${text}`].filter((changed) => changed !== text);

expect(holdouts.length).toBe(rules.length);
for (const [index, rule] of rules.entries()) {
  test(`T3 sentence: ${rule[0]} rejects removal/inversion and accepts holdout`, () => {
    const source = sentences(runtime());
    const matching = source.filter((sentence) => accepts(sentence, rule));
    expect(matching.length, `missing rule: ${rule[0]}`).toBeGreaterThan(0);
    expect(source.filter((sentence) => !matching.includes(sentence)).some((sentence) => accepts(sentence, rule))).toBe(false);
    expect(accepts(holdouts[index], rule), `holdout: ${holdouts[index]}`).toBe(true);
    for (const sentence of [...matching, holdouts[index]]) {
      for (const changed of inversions(sentence)) {
        expect(accepts(changed, rule), `${rule[0]}: ${changed}`).toBe(false);
      }
    }
  });
}

// Each scenario names the sentence checks that must remain in the reference.
// Action concepts are order-free and are checked in the fixture and reference.
const recovery = {
  'lost-launch-response': {
    'key and title': ['key and title'],
    'launch recovery inventory': ['launch recovery inventory', 'reserved branch', 'unreconciled worktree'],
    'launch recovery outcomes': ['launch recovery outcomes', 'relaunch absence', 'recovery hold', 'silence duplicate'],
  },
  'silent-provisioning-failure': {
    'SHA baseRef': ['SHA baseRef', 'baseRef commit'],
    'post-launch wait': ['post-launch wait', 'timed-out started', 'preparing hold'],
    'failure classification': ['failure classification'],
  },
  'writer-death-after-idle': {
    'idle writer watch': ['idle writer watch', 'watch reconcile', 'watch failure'],
    'failure classification': ['failure classification'],
    'replacement attempt': ['replacement attempt', 'failed branch salvage', 'unknown writer liveness', 'replacement reconcile'],
  },
  'stale-completion': {
    'stale completion': ['current completion', 'stale completion', 'stale receipt evidence'],
    'status persistence': ['status persistence'],
    'writer completion': ['writer completion'],
  },
  'child-question-resume': {
    'delegate completion': ['delegate completion', 'question incomplete'],
    'question resume': ['question resume', 'resumed result', 'question notification'],
    'status persistence': ['status persistence'],
  },
};
const actions = {
  'lost-launch-response': [
    ['launch recovery outcomes', [/adopt/i, /one exact match/i]],
    ['reserved branch', [/keep/i, /reserved branch/i]],
    ['relaunch absence', [/relaunch once/i, /proven absence/i]],
    ['recovery hold', [/matches/i, /incomplete inventory/i, /hold/i]],
  ],
  'silent-provisioning-failure': [
    ['post-launch wait', [/launch failure/i]],
    ['timed-out started', [/activeRunId/, /worktreePath/, /started/i]],
    ['preparing hold', [/still preparing/i, /hold/i, /next wake/i]],
  ],
  'writer-death-after-idle': [
    ['watch failure', [/failed run/i, /hold/i, /incomplete/i]],
    ['replacement attempt', [/terminal failure/i, /a<n\+1>/]],
    ['failed branch salvage', [/failed/i, /branch/i, /salvage/i]],
  ],
  'stale-completion': [
    ['stale receipt evidence', [/receipt/i, /evidence/i]],
    ['status persistence', [/persist/i, /task_status/, /before/i, /t3_thread_read|thread reads/i]],
    ['writer completion', [/require/i, /terminal/i]],
    ['current completion', [/current attempt/i, /SHA/]],
  ],
  'child-question-resume': [
    ['question resume', [/answer once/i, /t3_thread_send/, /childThreadId/, /600000/, /watch/i]],
    ['resumed result', [/accept only/i, /latestTerminal/, /newer than/i, /question run/i]],
  ],
};

test('AC2 recovery actions stay bound to sentence contracts', () => {
  const scenarios = JSON.parse(read('tests/workflows/t3-recovery-scenarios.json'));
  expect(scenarios.cases.slice(0, 5).map(({ id }) => id)).toEqual(Object.keys(recovery));
  for (const scenario of scenarios.cases.slice(0, 5)) {
    expect(scenario.input).toBeTruthy();
    expect(scenario.contracts).toEqual(Object.keys(recovery[scenario.id]));
    for (const name of Object.values(recovery[scenario.id]).flat()) {
      const rule = rules.find(([id]) => id === name);
      expect(rule, name).toBeDefined();
      expect(accepts(runtime(), rule), `${scenario.id}: ${name}`).toBe(true);
    }
    for (const [name, concepts] of actions[scenario.id]) {
      expect(concepts.every((concept) => concept.test(scenario.expected.action)), `${scenario.id}: action ${name}`).toBe(true);
      const rule = rules.find(([id]) => id === name);
      const instruction = sentences(runtime()).find((sentence) => accepts(sentence, rule));
      expect(concepts.every((concept) => concept.test(instruction)), name).toBe(true);
      for (const concept of concepts) {
        const removed = scenario.expected.action.replace(new RegExp(concept.source, 'gi'), '');
        expect(concepts.every((check) => check.test(removed)), `${scenario.id}: removed action`).toBe(false);
      }
    }
  }
});
