import { expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { sentences, requires, prohibits } from './prose-contract.js';

const read = (path) => readFileSync(`${import.meta.dir}/../../${path}`, 'utf8');
const runtime = () => read('skills/axstack/references/t3-runtime.md').replace(/[`*]/g, '').replace(/^#+.*$/gm, '').replace(/\|\n/g, '|.\n');
// Concepts co-occur in ONE sentence, in any order. Negative rules carry an
// explicit prohibition phrase; all other denial words still invalidate it.
const accepts = (text, [, concepts, prohibition]) => prohibition
  ? prohibits(text, prohibition, ...concepts) : requires(text, ...concepts);
const rules = [
  ['capabilities', [/driver/i, /T3 thread/i, /sav\w*/i, /orchestrator_capabilities/, /JSON/, /schema/i]],
  ['missing capability', [/missing capability/i, /hold/i, /affected operation/i], /without a substitute runtime/i],
  ['role snapshot', [/roles.json/, /snapshot/i, /preset/i, /stable role IDs/i, /requested/i, /resolved/i, /source/i, /time/i]],
  ['snapshot resume', [/resume/i, /snapshot/i], /no re-resolution/i],
  ['snapshot change', [/changes/i, /require/i, /user/i, /explicit decision/i]],
  ['provider mapping', [/bindings/i, /codex→codex/, /claude→claudeAgent/, /grok→grok/, /antigravity→antigravity/]],
  ['mode and options', [/modeId/, /runtimeMode:full-access/, /options:\[\{id,value\}\]/]],
  ['pinned model', [/preset model/i, /used|use/i, /as given/i]],
  ['class resolution', [/modelClass/, /resolve/i, /newest/i, /provider/i, /gpt-<N>-<class>/, /claude-<class>-<N>-<N>/]],
  ['resolution catalog', [/resolve-models.js/, /--provider/, /saved capabilities JSON path/i]],
  ['catalog hold', [/missing|malformed/i, /catalog/i, /hold/i, /resolution/i]],
  ['null model', [/model:null/, /first model/i, /provider/i, /saved capabilities/i], /no class/i],
  ['null ID receipt', [/record/i, /exact ID/i, /unresolved provider default/i]],
  ['availability hold', [/unavailable/i, /provider/i, /model/i, /role/i, /mode/i, /effort/i, /hold/i], /no substitution/i],
  ['no alternative on failure', [/auth/i, /quota/i, /timeout/i, /rejection/i, /alternative/i], /do not select|never select/i],
  ['absent seats', [/intentional/i, /absent seats/i, /recorded absences/i]],
  ['runtime availability', [/availability/i, /runtime proof/i]],
  ['codex effort', [/codex/i, /effort/i, /option ID/i, /reasoningEffort/]],
  ['claude effort', [/claude/i, /effort/i, /option ID effort/i]],
  ['grok effort', [/grok/i, /reasoningEffort/, /exclude max/i]],
  ['Grok CLI floor', [/CLI/, /requires|must/i, /≥1\.0\.13/]],
  ['Grok readiness proof', [/grok/i, /alone/i, /prove|establish/i, /CLI/i, /runs/i], /does not|cannot/i],
  ['opencode effort', [/opencode/i, /effort/i, /variant/], /no OpenCode role enters this migration/i],
  ['binding echo', [/dispatch echo/i, /match/i, /requested/i, /provider/i, /model/i]],
  ['binding readback', [/verify/i, /options/i, /runtimeMode/, /t3_thread_configuration/, /read.back/i]],
  ['separate binding evidence', [/record|keep/i, /requested/i, /effective/i, /separat/i]],
  ['worker proof', [/worker self.report/i, /configuration proof/i], /not|never/i],
  ['missing effort readback', [/missing effort read.back/i, /hold/i, /roles/i, /effort/i]],
  ['effort satisfaction', [/record/i, /satisfied/i], /never record/i],
  ['other effort limitation', [/other providers/i, /effort read.back/i, /unverified/i, /exercised|tested/i]],
  ['first configuration canary', [/first dispatch/i, /provider/i, /model/i, /effort/i, /running/i, /completed/i, /before/i, /siblings/i]],
  ['canary rejection', [/rejection/i, /stop|block/i, /siblings/i, /configuration/i]],
  ['unrelated configurations', [/unrelated configurations/i, /eligible|admissible/i]],
  ['read-only delegates', [/advisers/i, /research/i, /diligence/i, /delegate_task/, /async/i, /driver worktree/i, /title = dispatch key/i]],
  ['delegate untouched', [/tracked/i, /untracked/i, /files/i, /untouched/i]],
  ['delegate evidence', [/writes only/i, /<run>\/evidence\/<key>\//]],
  ['probe delegates', [/reviewers/i, /debug investigators/i, /execution investigators/i, /UI verifier/i, /delegate_task/, /async/i, /title = dispatch key/i]],
  ['probe checkout', [/disposable/i, /detached/i, /candidate SHA/i, /pinned base/i, /git worktree add --detach/]],
  ['probe cd', [/brief/i, /requires/i, /cd/i, /into it/i]],
  ['probe outputs', [/disposable probes/i, /outputs/i, /<run>\/evidence\/<key>\//]],
  ['writer launch', [/author/i, /code-arena/i, /t3_thread_launch/, /type:worktree/, /startFromOrigin:false/, /own worktree/i, /merges or closes/i]],
  ['owner row', [/owner/i, /driver thread/i, /driver worktree/i]],
  ['owner source exclusion', [/tracked files/i], /never (?:writes|edits|changes) tracked files|never (?:written|edited|changed)/i],
  ['owner worker exclusion', [/worker launch/i], /No worker launch/i],
  ['driver ownership', [/driver/i, /sole run.record writer/i, /one writer per candidate/i]],
  ['driver source exclusion', [/tracked files/i, /repairs/i, /author/i, /source/i], /never writes/i],
  ['repair ownership', [/repairs/i, /return|go back/i, /that author|same author/i]],
  ['idle ownership', [/missing/i, /idle/i, /session/i, /ownership/i, /transfer/i], /no ownership transfer|never (?:grant ownership transfer|transfers?)/i],
  ['driver preset exclusion', [/current/i, /chat\/driver|driver/i, /preset/i], /no role (?:row|entry)/i],
  ['key and title', [/dispatch key/i, /<run>:<role>:<task>:a<n>/, /before/i, /launch/i, /exact whole/i, /T3 title/i]],
  ['substring identity', [/substring matches/i, /establish/i, /identity/i], /do not|not/i],
  ['branch naming', [/branch/i, /axstack\/<run>\/<role>\/<task>-a<n>/]],
  ['branch encoding', [/lowercase/i, /each segment/i, /replace/i, /\[\^a-z0-9-\]/, /with -/]],
  ['dispatch original', [/dispatch key/i, /original form/i, /record both/i]],
  ['normalization identity', [/normalization/i, /identity substitute/i], /never/i],
  ['SHA baseRef', [/baseRef/, /branch name/i], /never (?:be )?a branch name/i],
  ['baseRef commit', [/always (?:be )?a commit SHA/i], /never a branch name|^(?!.*branch name)/i],
  ['pinned dispatch revisions', [/pin/i, /base/i, /candidate/i, /before/i, /dispatch/i]],
  ['receipt protocol', [/workers/i, /exactly one final marker/i, /AXSTACK-DONE key=/, /head=/, /report=/, /AXSTACK-FAILED key=/, /AXSTACK-QUESTION key=/, /q=/]],
  ['report identity', [/reports/i, /absolute/i, /private evidence paths/i]],
  ['report-only head', [/report.only head/i, /pinned candidate SHA/i]],
  ['writer delivery', [/launched writers/i, /marker/i, /t3_thread_send/, /recorded driver thread/i]],
  ['delegate delivery', [/delegated children/i, /final result/i]],
  ['status persistence', [/driver/i, /persist/i, /task_status/, /private evidence/i, /before/i, /t3_thread_read/, /delegated task/i]],
  ['whole status', [/save/i, /whole response/i, /before/i, /consum|expand/i, /result/i]],
  ['delegate completion', [/delegated completion/i, /require/i, /terminal/i, /completed/, /result_available/, /hasPendingChildRuns:false/, /AXSTACK-DONE/]],
  ['question incomplete', [/question/i, /incomplete/i, /completed/i]],
  ['writer completion', [/launched writer completion/i, /require/i, /terminal/i, /t3_thread_wait/, /non.empty diff/i, /clean tree/i, /red\/green/i]],
  ['message progress', [/receipt message alone/i, /only/i, /progress/i]],
  ['current completion', [/completion/i, /current attempt key/i, /candidate SHA/i]],
  ['stale completion', [/older attempt/i, /complet\w*/i, /newer/i], /never/i],
  ['stale receipt evidence', [/stale/i, /duplicate receipts/i, /evidence/i, /deduplicated/i, /runtime identity/i]],
  ['delivery validation', [/whole delivery/i, /before/i, /acknowledgment/i, /advance only after/i, /sender/i, /scope/i, /artifacts/i]],
  ['failure classification', [/task_status failed/, /failed or interrupted/i, /preparing thread error/i, /AXSTACK-FAILED/, /incomplete outcome/i, /preserved evidence/i]],
  ['silence completion', [/silence/i, /successful completion/i], /not|never/i],
  ['delegated isolation', [/after each delegated completion/i, /driver/i, /HEAD/, /git status --porcelain/, /pre-dispatch/i, /unchanged/i, /untracked/i]],
  ['isolation hold', [/any change/i, /is a hold/i, /before/i, /advancing/i]],
  ['launch recovery inventory', [/lost launch response/i, /fully paginated/i, /t3_thread_list/, /titleContains=<key>/, /exact whole.title equality/i, /git worktree list/]],
  ['reserved branch', [/keep/i, /reserved branch/i, /recovery/i]],
  ['unreconciled worktree', [/branch/i, /worktree/i, /without a reconciled thread/i, /prevent\w*/i, /proof of absence/i], /without a reconciled thread/i],
  ['launch recovery outcomes', [/recovery/i, /adopt/i, /one exact match/i, /worktree/i, /branch/i, /agree/i]],
  ['relaunch absence', [/proven absence/i, /relaunch once/i, /same reserved key/i, /branch/i]],
  ['recovery hold', [/several matches/i, /conflicts/i, /second uncertain response/i, /incomplete inventory/i, /hold/i]],
  ['silence duplicate', [/duplicate writer/i, /silence/i, /launch|start|justif/i], /never/i],
  ['post-launch wait', [/post.launch/i, /driver/i, /t3_thread_wait/, /timeoutMs:120000/, /failed/i, /launch failure/i]],
  ['timed-out started', [/timed.out/i, /t3_thread_read/, /activeRunId/, /worktreePath/, /started/i]],
  ['preparing hold', [/still preparing/i, /is a hold/i, /re.read/i, /next wake/i]],
  ['unresolved launch', [/unresolved state/i, /preserve|retain/i, /attempt/i]],
  ['question resume', [/AXSTACK-QUESTION/, /answer once/i, /t3_thread_send/, /childThreadId/, /resumed runId/i, /t3_thread_wait/, /timeoutMs:600000/, /run watch/i]],
  ['resumed result', [/persist status/i, /accept only/i, /latestTerminal/, /newer than/i, /question run/i, /terminal success/i, /matching receipt key\/SHA/i], /not lexical ID order/i],
  ['question summary', [/original summary/i, /stable/i]],
  ['question notification', [/notification/i], /no notification/i],
  ['same writer repair', [/repair/i, /t3_thread_send/, /mode:queue/, /same author/i, /same attempt/i, /worktree/i]],
  ['repair revision', [/pin/i, /new candidate revision/i]],
  ['replacement attempt', [/replacement/i, /terminal failure/i, /a<n\+1>/, /new branch/i, /title/i]],
  ['failed branch salvage', [/failed attempt/i, /branch/i, /kept/i, /until salvage/i]],
  ['unknown writer liveness', [/unknown liveness/i, /holds/i, /replacement/i]],
  ['replacement reconcile', [/reconcile/i, /old writer/i, /before/i, /another/i]],
  ['idle writer watch', [/unsettled launched thread/i, /turn/i, /end only/i, /schedule_task/, /bindToCurrentThread:true/, /everyMs:600000/, /armed/i, /ID recorded/i]],
  ['watch reconcile', [/each wake/i, /reconcile all unsettled runs/i, /writer/i, /died/i, /without sending|silently/i]],
  ['watch failure', [/failed runs/i, /hold|held/i, /incomplete work/i]],
  ['watch deletion', [/nothing/i, /unsettled/i, /delete_scheduled_task/, /list_scheduled_tasks/, /read back/i, /absence/i]],
  ['uncertain watch deletion', [/uncertain delete/i, /preserve|retain/i, /hold/i, /recorded ID/i]],
  ['safe deletion in briefs', [/put|include/i, /safe.deletion rule/i, /every worker brief/i]],
  ['named private evidence', [/name|identify/i, /private/i, /<run>\/evidence\/<key>\//, /brief/i, /completion receipt/i]],
  ['temporary evidence guard', [/before/i, /use/i, /cleanup/i, /TMPDIR/, /0700/, /owned/i, /real path/i, /inside/i, /recorded run evidence/i, /owner/i], /no symlink/i],
  ['worktree path guards', [/equivalent guards/i, /worktree.local paths/i]],
  ['uncertain path retention', [/uncertain paths/i, /preserved/i, /reconciliation/i]],
  ['safe deletion', [/deletion/i, /exact validated owned path/i, /evidence/i, /TMPDIR/, /worktree/i, /literal absolute path/i, /\$\{VAR:\?\}/, /no glob/i, /no parent.root deletion/i], /no glob|no parent.root deletion/gi],
  ['glob deletion', [/no glob/i, /no parent.root deletion/i], /no glob|no parent.root deletion/gi],
  ['parent deletion', [/no parent.root deletion/i, /no glob/i], /no glob|no parent.root deletion/gi],
  ['cache deletion', [/general cache/i], /never wipe a general cache/i],
  ['cache evidence', [/incidental caches/i, /evidence/i], /not/i],
  ['brief confirmation', [/dispatching owner/i, /confirm/i, /brief question once/i, /existing authority/i, /re.verify/i, /started/i]],
  ['second brief hold', [/second ask/i, /holds/i]],
  ['prompt refusal', [/answer/i, /trust/i, /permission prompts/i], /never/i],
  ['confirmation authority', [/brief confirmation/i, /no authority/i, /harness/i, /tool dialog/i, /does not answer/i], /no authority|does not answer/gi],
  ['prompt refusal hold', [/permission prompt/i, /provider safety refusal/i, /held/i, /incomplete outcome/i]],
  ['refusal bypass', [/bypass/i, /retry/i, /another model/i], /never/i],
  ['additional prompt holds', [/trust/i, /hook review/i, /authentication/i, /model prompts/i, /hold/i]],
  ['prompt recovery evidence', [/preserve/i, /attempt/i, /inspect/i, /native state/i, /before/i, /authorized recovery/i]],
  ['review evidence isolation', [/each reviewer/i, /separate checkout/i, /private evidence folder/i], /no first-pass cross-read/i],
  ['review tracked files', [/tracked candidate files/i, /read.only/i]],
  ['review evidence readback', [/read back/i, /report/i, /supporting evidence/i, /before/i, /removing/i, /checkout/i]],
  ['external evidence', [/evidence/i, /outside/i, /archive/i], /no archive/i],
  ['fresh review', [/later review/i, /fresh checkout/i]],
  ['fresh review retention', [/unknown/i, /active evidence/i, /unique bytes/i, /preserved/i]],
  ['untracked retention', [/untracked files/i, /worktree/i, /disposable/i, /prov|establish/i], /never|cannot/i],
  ['terminal evidence retention', [/T3 terminal state alone/i, /discarding evidence/i, /authoriz/i], /does not|cannot|not/i],
  ['acceptance distinct from start', [/input acceptance/i, /started state/i, /effective settings/i, /completed work/i, /distinct evidence/i]],
  ['silence exit', [/silence/i, /contact loss/i, /idle state/i, /prov\w*/i, /exit/i], /never/i],
  ['resume ownership', [/ordinary resume/i, /same owner/i, /author/i, /attempt/i, /worktree/i, /revisions/i, /pending receipts/i]],
  ['uncertain replacement', [/uncertainty/i, /holds/i, /replacement/i]],
  ['ownership transfer', [/explicit user transfer/i, /recipient acceptance/i, /session/i, /scope/i, /revision/i, /authority/i, /before/i, /ownership/i]],
  ['current owner accountability', [/current owner/i, /accountab\w*/i, /until then/i]],
  ['prior owner stop', [/prior owner/i, /stops/i, /after acceptance/i]],
  ['transfer receipt boundary', [/input acceptance/i, /turn start alone/i, /transfer receipt/i], /no transfer receipt|cannot be a transfer receipt/i],
  ['runtime identity mismatch', [/T3/, /threadId\/runId/, /mismatch/i, /stop consuming/i, /reconcile/i, /driver identity/i, /native state/i]],
  ['identity forgery', [/forg\w*/i, /sender/i, /borrow\w*/i, /identity/i, /bypass/i, /mismatch/i], /never/i],
  ['user takeover retention', [/driver/i, /retain/i, /user.taken.over T3 thread/i]],
  ['user takeover cleanup', [/cleanup commands/i, /t3_thread_organize/, /settle/i, /archive/i], /never send/i],
  ['T3 settle evidence', [/require/i, /T3 terminal run evidence/i, /before/i, /t3_thread_organize/, /settle/i, /archive/i]],
  ['T3 metadata boundary', [/metadata actions/i, /worktree removal/i], /not/i],
  ['cleanup preflight', [/worktreeCleanup/, /off/, /every Axstack project/i]],
  ['cleanup readback', [/preflight/i, /t3_project_read/, /where exposed/i]],
  ['cleanup limitation', [/otherwise/i, /record a limitation/i, /documented/i, /installation setup step/i]],
  ['cleanup evidence priority', [/automatic worktree deletion/i, /evidence readback/i, /salvage/i], /cannot replace|no substitute for/i],
  ['run record', [/run record/i, /driver threadId/, /projectId/, /host/i, /T3 version/, /installed Axstack SHA/, /capabilities JSON path/, /scheduledTaskIds/, /watch/i, /manager schedule/i]],
  ['dispatch target record', [/per dispatch/i, /record/i, /key/i, /mechanism/i, /requested target/i, /read.back/i]],
  ['dispatch identity record', [/taskId\/childThreadId\/childRunId/, /threadId\/runId\/worktree\/branch\/base SHA/]],
  ['dispatch revision record', [/checkout path/i, /candidate/i, /base SHAs/i]],
  ['dispatch evidence record', [/evidence folder/i, /scope\/authority/i, /owner/i, /pending receipts/i, /hold/i, /Next/]],
  ['native runtime boundary', [/boundary/i, /Axstack daemon/i, /DB/, /lock/i, /scheduler/i], /no Axstack daemon/i],
  ['publication authority', [/private evidence/i, /requires/i, /explicit publication authority/i, /before sharing/i]],
  ['receipt authority', [/receipts/i, /merge/i, /release/i, /publication/i, /model.substitution/i, /host.mutation/i, /expanded scope authority/i], /no merge/i],
  ['human merge authority', [/human/i, /merges/i, /by default/i]],
];

